// Generated by tools/generateAssessmentRegistry.ts. Do not edit manually.
import assessmentPackage0 from "../content/tests/animal-personality-6/test.json";
import assessmentPackage1 from "../content/tests/demo-personality/test.json";
import assessmentPackage2 from "../content/tests/demo-ranking/test.json";
import assessmentPackage3 from "../content/tests/demo-relationship/test.json";
import assessmentPackage4 from "../content/tests/hidden-career-talent-cn/test.json";
import assessmentPackage5 from "../content/tests/matchmaking-market-positioning-v2/test.json";
import assessmentPackage6 from "../content/tests/soul-city-china/test.json";
import assessmentPackage7 from "../content/tests/two-person-relationship-fit/test.json";

export const discoveredAssessmentPackages: ReadonlyArray<{ source: string; packageData: unknown }> = [
  { source: "content/tests/animal-personality-6/test.json", packageData: assessmentPackage0 },
  { source: "content/tests/demo-personality/test.json", packageData: assessmentPackage1 },
  { source: "content/tests/demo-ranking/test.json", packageData: assessmentPackage2 },
  { source: "content/tests/demo-relationship/test.json", packageData: assessmentPackage3 },
  { source: "content/tests/hidden-career-talent-cn/test.json", packageData: assessmentPackage4 },
  { source: "content/tests/matchmaking-market-positioning-v2/test.json", packageData: assessmentPackage5 },
  { source: "content/tests/soul-city-china/test.json", packageData: assessmentPackage6 },
  { source: "content/tests/two-person-relationship-fit/test.json", packageData: assessmentPackage7 }
];
