import { readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const defaultTestsRoot = resolve(projectRoot, "content", "tests");
const registryOutput = resolve(projectRoot, "registry", "generatedAssessmentPackages.ts");

export interface DiscoveredTestPackage {
  source: string;
  packageFile: string;
  packageData: unknown;
}

export async function discoverTestPackageFiles(testsRoot = defaultTestsRoot): Promise<string[]> {
  const entries = await readdir(testsRoot, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => resolve(testsRoot, entry.name, "test.json"))
    .sort((left, right) => left.localeCompare(right));
}

export async function loadTestPackages(testsRoot = defaultTestsRoot): Promise<DiscoveredTestPackage[]> {
  const packageFiles = await discoverTestPackageFiles(testsRoot);
  const discovered: DiscoveredTestPackage[] = [];
  for (const packageFile of packageFiles) {
    try {
      const json = await readFile(packageFile, "utf8");
      discovered.push({
        source: relative(projectRoot, packageFile).split(sep).join("/"),
        packageFile,
        packageData: JSON.parse(json)
      });
    } catch (error) {
      const reason = error instanceof Error ? error.message : String(error);
      throw new Error(`Unable to load Test Package ${packageFile}: ${reason}`);
    }
  }
  return discovered;
}

export async function generateAssessmentRegistry(packages?: readonly DiscoveredTestPackage[]): Promise<void> {
  const discoveredPackages = packages ?? (await loadTestPackages());
  if (discoveredPackages.length === 0) {
    throw new Error(`No Test Packages found in ${defaultTestsRoot}`);
  }

  const imports = discoveredPackages.map((testPackage, index) => {
    const importPath = toImportPath(relative(dirname(registryOutput), testPackage.packageFile));
    return `import assessmentPackage${index} from "${importPath}";`;
  });
  const entries = discoveredPackages.map((testPackage, index) => {
    return `  { source: "${testPackage.source}", packageData: assessmentPackage${index} }`;
  });
  const output = [
    "// Generated by tools/generateAssessmentRegistry.ts. Do not edit manually.",
    ...imports,
    "",
    "export const discoveredAssessmentPackages: ReadonlyArray<{ source: string; packageData: unknown }> = [",
    entries.join(",\n"),
    "];",
    ""
  ].join("\n");

  await writeFile(registryOutput, output, "utf8");
}

function toImportPath(path: string): string {
  const normalized = path.split(sep).join("/");
  return normalized.startsWith(".") ? normalized : `./${normalized}`;
}

const invokedPath = process.argv[1] ? resolve(process.argv[1]) : undefined;
if (invokedPath === fileURLToPath(import.meta.url)) {
  await generateAssessmentRegistry();
}
